// Official screen swatches from https://clairefontaine.eu/en/papers/trophee/#specs
export const tropheeColors = [
  { name: "Pearl grey", hex: "#eceade" },
  { name: "Steel grey", hex: "#dad5d2" },
  { name: "Cream", hex: "#fef7e4" },
  { name: "Chamois", hex: "#f4e4c0" },
  { name: "Caramel", hex: "#c6a477" },
  { name: "Orange", hex: "#e3aa73" },
  { name: "Apricot", hex: "#f1cb9c" },
  { name: "Peach", hex: "#e9bbac" },
  { name: "Gold", hex: "#f3d068" },
  { name: "Daffodil", hex: "#fdf69e" },
  { name: "Canary", hex: "#fbf0b0" },
  { name: "Salmon", hex: "#f4d8cd" },
  { name: "Pink", hex: "#f2dcdf" },
  { name: "Lilac", hex: "#dbd7ee" },
  { name: "Wild rose", hex: "#de9ec3" },
  { name: "Lavander", hex: "#a2badc" },
  { name: "Dark blue", hex: "#b1d5e1" },
  { name: "Nature green", hex: "#c8e1c4" },
  { name: "Sky blue", hex: "#73cbf4" },
  { name: "Blue", hex: "#9fd5f9" },
  { name: "Jade", hex: "#deeaa4" },
  { name: "Green", hex: "#d7eaaf" },
  { name: "Pale green", hex: "#eef7e1" },
  { name: "Flame", hex: "#e09017" },
  { name: "Intensive orange", hex: "#cb4e14" },
  { name: "Coral red", hex: "#c10212" },
  { name: "Intensive red", hex: "#ac1751" },
  { name: "Intensive pink", hex: "#d46d9a" },
  { name: "Intensive Lilac", hex: "#776daa" },
  { name: "Royal Blue", hex: "#6bb9dd" },
  { name: "Intensive blue", hex: "#478dc8" },
  { name: "Intensive yellow", hex: "#ffec02" },
  { name: "Yellow sunflower", hex: "#e7bb27" },
  { name: "Intensive green", hex: "#a3bd38" },
  { name: "Billiard green", hex: "#76a85f" },
  { name: "Forest green", hex: "#226b4e" },
  { name: "Black", hex: "#010101" },
  { name: "Fluo pink", hex: "#c5027c" },
  { name: "Fluo yellow", hex: "#f6e80d" },
  { name: "Fluo green", hex: "#b9c932" },
  { name: "Fluo orange", hex: "#e2a415" },
] as const
